{% set name = "loopy" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/Loop3D/loopy-conda.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - cython
    - numpy
    - python
    - pybind11
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - geopandas
    - pyproj
    - shapely
    - rasterio
    - descartes
    - matplotlib-base
    - networkx
    - scipy
    - owslib
    - tqdm
    - map2model
    - mplstereonet
    - hjson
    - loopprojectfile
    - cftime=1.4.0
    - scikit-image
    - scikit-learn
    - pyamg

test:
  imports:
   - loopy

about:
  home: "https://github.com/Loop3D/loopy-conda.git"
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "Loop's complete workflow for 3D geological modelling."

extra:
  recipe-maintainers:
    - yohanderose
    - lachlangrose
